name: moinsen_cli
description: Moinsen - The flutter kick-starter CLI.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  args: ^2.3.1
  glob: ^2.1.0
  lcov_parser: ^0.1.2
  mason: ^0.1.0-dev.34
  mason_logger: ^0.2.0
  meta: ^1.8.0
  path: ^1.8.2
  pub_updater: ^0.2.1
  pubspec_parse: ^1.2.1
  stack_trace: ^1.11.0
  universal_io: ^2.0.4
  very_good_test_runner: ^0.1.2

dev_dependencies:
  build_runner: ^2.0.0
  build_verify: ^3.0.0
  build_version: ^2.0.0
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.1.0

executables:
  moinsen: